# syntax=docker/dockerfile:1
FROM ruby:2.7.3
RUN apt-get update -qq && apt-get install -y build-essential libpq-dev postgresql-client
RUN mkdir /lafiga-api
WORKDIR /lafiga-api
COPY ./config/Gemfile /lafiga-api/Gemfile
#COPY ./config/Gemfile.lock /lafiga-api/Gemfile.lock
RUN gem install bundler:2.2.17
RUN bundle install
RUN bundle update listen


# Add a script to be executed every time the container starts. comentario denescessário
COPY ./config/entrypoint.sh /usr/bin/
RUN chmod +x /usr/bin/entrypoint.sh
ENTRYPOINT ["entrypoint.sh"]

# Configure the main process to run when running the image
CMD ["rails", "server", "-b", "0.0.0.0"]